name: Update the Arch Linux version

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Arch Linux Latest Version
        id: get_arch_version
        uses: ./.github/actions/get-arch-version
        with:
          archive_url: 'https://archive.archlinux.org/iso/'

      - name: Compare Versions
        run: |
          echo "Latest Arch Linux version is ${{ steps.get_arch_version.outputs.version }}"
          if [ "$(cat VERSION)" != "${{ steps.get_arch_version.outputs.version }}" ]; then
            echo "Version mismatch, triggering release"
            echo "${{ steps.get_arch_version.outputs.version }}" > VERSION
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add VERSION
            git commit -m "chore: bump version to ${{ steps.get_arch_version.outputs.version }}"
            git push
          else
            echo "Version match, no action required"
          fi
